<?php

function statsform_menu() {
  $items = array();
  
  $items['statsform/form'] = array(
    'title' => 'Stats Form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('statsform_form'),
    'access callback' => TRUE,
    'description' => 'For statsform use',
  );
  $items['statsform/references'] = array(
    'title' => 'Stats Form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('statsform_references'),
    'access callback' => TRUE,
    'description' => 'For statsform use',
  );
  $items['statsform/mockup'] = array(
    'title' => 'Stats Form',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('statsform_mockup'),
    'access callback' => TRUE,
    'description' => 'For statsform use',
  );
 
 
  return $items;
}

function statsform_html_head_alter(&$head_elements) {

  // Force the latest IE rendering engine and Google Chrome Frame.
  $head_elements['chrome_frame'] = array(
    '#type' => 'html_tag',
    '#tag' => 'meta',
    '#attributes' => array('http-equiv' => 'X-UA-Compatible', 'content' => 'IE=edge,chrome=1'),
  );
}

function hook_page_alter(&$page) {
  // Add help text to the user login block.
  $page['sidebar_first']['user_login']['help'] = array(
    '#weight' => -10,
    '#markup' => t('To post comments or add new content, you first have to log in.'),
  );
}

function statsform_form($form, &$form_state) {
    
      

 
  $form['home'] = array(
        '#type' => 'item',

        '#markup' => '
        
<html>
    <head>
        <title>Stats Redesign Project</title>

        <!-- JQuery -->
        <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.1.1.min.js"></script>

        <!-- Semantic UI -->
        <link rel="stylesheet" type="text/css" href="../semantic/semantic.min.css">
        <script src="../semantic/semantic.min.js"></script>

        <!-- Personally Defined CSS/Javascript -->
        <link rel="stylesheet" type="text/css" href="../css/stylesheet.css">
        <script src="../js/javascript.js"></script>


        <!-- Google Font Montserrat --> 

        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">   


    </head>
    <body>

        <!-- Menu -->
        <div class="ui secondary inverted menu">
            <div class="ui huge breadcrumb">
                <div class="active section" >
                    <a class="item">
                        Home
                    </a>
                </div>
            </div>
            <div class="right menu">
                <a class="item">
                    Login
                </a>
            </div>
        </div>

        <!-- Content -->
        <div class="ui equal width height center aligned grid">
         <div class="row">
          <a class="six wide column" href="references" id="YRL"> <div class="verticalalign"> YOUNG RESEARCH LIBRARY</div></a>
          <div class="four wide column">
            <img class ="img-responsive" src="../img/Statsform_Stock_Photos/powellnight.jpg">
        </div>
        <a class="six wide column" href="references" id="BL"> <div class="verticalalign"> BIOMEDICAL LIBRARY </div> </a>
    </div>

    <div class="row">
        <div class="four wide column"> <div align="left">
           <img class ="img-responsive" src="../img/Statsform_Stock_Photos/powellstudent.jpg"></div>
       </div>
       <a class="seven wide column" href="references" id = "POWELL"> <div class="verticalalign">POWELL LIBRARY</div></a> 
       <div class="five wide column">
        <img class ="img-responsive" src="../img/Statsform_Stock_Photos/clicc.jpg"></div>
    </div>


    <div class="row">
        <div class="four wide column">
            <img class ="img-responsive" src="../img/Statsform_Stock_Photos/books.jpg">
        </div>
        <a class="four wide column" href="references" id="AL"><div class="verticalalign"> ARTS LIBRARY</div></a>
        <div class="four wide column">
            <img class ="img-responsive" src="../img/Statsform_Stock_Photos/DAY3_SHOT5_YOUNGLIBRARY-2192_r_cmyk.jpg">
        </div>
        <a class="four wide column" href="references" id="ML"><div class="verticalalign">MUSIC LIBRARY</div></a>
    </div>
</div>    
</body>
</html>
        
        ',
    );
       $form['test'] = array(
    '#type'  => 'checkboxes',
    '#options' => drupal_map_assoc(  array( t('Test - checking this checkbox allows deletion of an expired reservation before 24 hours has passed') )  ),
  );

  $form['next'] = array(
    '#type'  => 'submit',
    '#value' => t('Start'),
    '#submit' => array('rc_res_form_page_one_handler_submit'),
  );
   
  return $form;
}

function statsform_references($form, &$form_state) {
    
  krumo($form_state['home']);
   krumo($form_state['values']);
 
 
  $form['ref'] = array(
        '#type' => 'item',
        '#markup' => '
        
<html>
<head>
    <title>Stats Redesign Project</title>

    <!-- Semantic UI -->
    <link rel="stylesheet" type="text/css" href="../assets/includes/semantic.min.css">
    <script type="text/javascript" src="../assets/includes/semantic.min.js"></script>

    <!-- JQuery -->
    <script type="text/javascript" src="../assets/includes/jquery.min.js"></script>

    <!-- Customization -->
    <link rel="stylesheet" type="text/css" href="../css/stylesheet.css" />
    <!-- IScroll Link here -->
    <script type="text/javascript" src="../css/stylesheet.css"></script>
</head>
<body>

    <!-- Menu -->
    <div class="ui secondary inverted menu">
        <div class="ui huge breadcrumb">
            <div class="section" >
                <a class="item" href="index.html">
                    Home
                </a>
            </div>
            <i class="right chevron icon divider"></i>
            <div class="active section">
                <a class="item">
                    Specific Library
                </a>
            </div>
        </div>
        <div class="right menu">
            <a class="item">
                Login
            </a>
        </div>
    </div>

    <!-- Content -->


    <div class="ui equal width center aligned grid">

<div class = "eight wide column" id="sec1"  >
 <a href = "mockup" > 
    <div class="containerBox">
    <div class="text-box">
        <h4>TAP</h4>
    </div>
    <img src="../img/Statsform_Stock_Photos/powellnight.jpg"/>
</div>
</a>
</div>

        <a href = "mockup"class="eight wide column" id="sec2"> <div class="verticalalign">ACCORDION</div></a>
        <a href = "mockup"class="eight wide column" id="sec3"><div class="verticalalign">SWIPE</div></a>
        <a href = "mockup"class="eight wide column" id="sec4"><div class="verticalalign">TABULAR</div></a>
        <a href = "mockup"class="eight wide column" id="sec5"><div class="verticalalign">ORIGINAL</div></a>
        <a href = "mockup" class="eight wide column" id="sec6"><div class="verticalalign">OTHER  </div></a>
    </div>    


<!-- <div class="containerBox">
    <div class="text-box">
        <h4>Your Text is responsive and centered</h4>
    </div>
    <img class="img-responsive" src="http://placehold.it/900x100"/>
</div>
 
 ** Attempted to create hyperlink photo with text on top. 3/1
!-->

</body>
</html>
        
        ',
        
    );
     
 
  return $form;
}

function statsform_mockup($form, &$form_state) {
  
  krumo($form_state['values']);
 
  $form['test'] = array(
        '#type' => 'item',
        '#markup' => '
<html>
<head>
    <title>Mockup</title>

    <!-- Include meta tag to ensure proper rendering and touch zooming -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Include jQuery Mobile stylesheets -->
    <link rel="stylesheet" href="https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css">

    <!-- Include the jQuery library -->
    <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>

    <!-- Include the jQuery Mobile library -->
    <script src="https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>

    <!-- Semantic UI -->
    <link rel="stylesheet" type="text/css" href="../assets/includes/semantic.min.css?v=1">
    <script type="text/javascript" src="../assets/includes/semantic.min.js?v=1"></script>
    <link rel="stylesheet" href="../assets/includes/calendar/dist/calendar.min.css">
    <script type="text/javascript" src="../assets/includes/calendar/dist/calendar.min.js"></script>
    <script scr="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.4/components/accordion.js"></script>


    <!-- Customization -->
    <link rel="stylesheet" type="text/css" href="../assets/includes/custom.accordion.css?v=1" />
    <!-- IScroll Link here -->
    <script type="text/javascript" src="../assets/includes/custom.accordion.js?v=1"></script>


</head>
<body>

    <div class="ui secondary inverted menu">
        <div class="ui huge breadcrumb">
            <div class="section" >
                <a class="item" href="index.html" rel="external" data-ajax="false">
                    Home
                </a>
            </div>
            <i class="right chevron icon divider"></i>
            <div class="section">
                <a class="item" href="../references.html" rel="external" data-ajax="false">
                    Specific Library
                </a>
            </div>
            <i class="right chevron icon divider"></i>
            <div class="active section">
                <a class="item">
                    Stats Form
                </a>
            </div>
        </div>
        <div class="right menu">
            <a class="item">
                Login
            </a>
        </div>
    </div>

    <!-- Calendar -->
    <script>
  $( function() {
    $( "#datepicker" ).datepicker();
  } );
  </script>
    <h3>Date only</h3>
  <div class="ui calendar" id="calendar">
    <div class="ui input left icon">
      <i class="calendar icon"></i>
      <input type="text" id="datepicker" placeholder="      Date">
    </div>
  </div>
  <br/>


    <!-- Accordion Start -->
    <div class="ui styled accordion">

        <!-- Quick Questions Section -->
        <div class="active title">
            <i class="dropdown icon"></i>
            Quick Questions
        </div>
        <div class="active content">
            <div class="ui equal width aligned grid">
                <div class="eight wide column"> 
                    <div class="ui fluid card withCount">
                        <div class="content"> 
                            <div class="ui inverted segment left floated" id="directions"> 
                                <div class="ui tiny inverted statistics left floated"> 
                                    <div class="statistic">
                                        <div class="value"> 0 
                                        </div> 
                                        <div class="label"> Count </div>
                                    </div>
                                </div>
                            </div>
                            <img class="ui tiny image left floated" src="../../img/directions.png"> 
                            <div class="header"> Directional </div> 
                            <div class="meta"> Location or directions provided. E.G. rooms, events, contact info, etc. </div> 
                        </div>
                    </div>
                </div>
                <div class="eight wide column"> 
                    <div class="ui fluid card withCount">
                        <div class="content">
                            <div class="ui inverted segment left floated" id="lookup">
                                <div class="ui tiny inverted statistics left floated"> 
                                    <div class="statistic">
                                        <div class="value"> 0
                                        </div> 
                                        <div class="label"> Count </div>
                                    </div>
                                </div>
                            </div>
                            <img class="ui tiny image left floated" src="../../img/lookup.png"> 
                            <div class="header"> Look Up Known Item </div>
                            <div class="meta"> Find call numbers, books, articles, locations, etc. for known items requested by patron. </div>
                        </div> 
                    </div>

                </div>
                <div class="eight wide column"> 
                    <div class="ui fluid card withCount">
                        <div class="content">
                            <div class="ui inverted segment left floated" id="policy">
                                <div class="ui tiny inverted statistics left floated"> 
                                    <div class="statistic">
                                        <div class="value"> 0
                                        </div> 
                                        <div class="label"> Count </div>
                                    </div>
                                </div>
                            </div>
                            <img class="ui tiny image left floated" src="../../img/policy.png"> 
                            <div class="header"> Policy & Operations</div>
                            <div class="meta"> Hours, access privileges, borrowing, reservations, other policies. </div>
                        </div> 
                    </div>
                </div>
                <div class="eight wide column"> 
                    <div class="ui fluid card withCount">
                        <div class="content">
                            <div class="ui inverted segment left floated" id="research">
                                <div class="ui tiny inverted statistics left floated"> 
                                    <div class="statistic">
                                        <div class="value"> 0
                                        </div> 
                                        <div class="label"> Count </div>
                                    </div>
                                </div>
                            </div>
                            <img class="ui tiny image left floated" src="../../img/research.png">
                            <div class="header"> Referral </div>
                            <div class="meta"> Referral to advance research support, library location, campus support, etc. </div>
                        </div> 
                    </div>
                </div>
                <div class="eight wide column"> 
                    <div class="ui fluid card withCount">
                        <div class="content">
                            <div class="ui inverted segment left floated" id="technical">
                                <div class="ui tiny inverted statistics left floated"> 
                                    <div class="statistic">
                                        <div class="value"> 0
                                        </div> 
                                        <div class="label"> Count </div>
                                    </div>
                                </div>
                            </div>
                            <img class="ui tiny image left floated" src="../../img/technical.png"> 
                            <div class="header"> Technical Assistance </div>
                            <div class="meta"> Help with printers, computers, software, scanners, etc. </div>
                        </div> 
                    </div>
                </div>
                <div class="eight wide column"> 
                    <div class="ui fluid card ">
                        <button style = "height: 120px" class=" ui button"> <h1 style = "font-size:70px"> SUBMIT </h1> </button>
                    </div>
                </div>


            </div>
        </div>





        <!-- Referral Section -->
        <div class="title">
            <i class="dropdown icon"></i>
            Research Assistance
        </div>
        <div class="content">
            <div class="ui equal width aligned grid">
                <div class="eight wide column">
                    <div class="ui fluid card">
                        <div class="content">
                            <img class="ui tiny image left floated" src="../../img/research.png"> 
                            <div class="header"> Research Assistance </div>
                            <div class="meta"> Help patron with research strategy, advice, overview of resources (drop-in). </div>
                        </div> 
                    </div>
                </div>
                <div class="eight wide column">
                    <div class="ui fluid card">
                        <div class="content">
                            <img class="ui tiny image left floated" src="../../img/technical.png"> 
                            <div class="header"> Technical Assistance </div>
                            <div class="meta"> Help with printers, computers, software, scanners, etc. </div>
                        </div> 
                    </div>
                </div>
                <div class="eight wide column">
                    <div class="ui fluid card">
                        <div class="content">
                            <img class="ui tiny image left floated" src="../../img/lookup.png"> 
                            <div class="header"> Look up Known Item </div>
                            <div class="meta"> Find call numbers, books, articles, locations, etc. for known items requested by patron. </div>
                        </div> 
                    </div>
                </div>
                <div class="eight wide column">
                    <div class="ui fluid card">
                        <div class="content">
                            <img class="ui tiny image left floated" src="../../img/directions.png"> 
                            <div class="header"> Directional </div>
                            <div class="meta"> Location or directions provided e.g. rooms, events, contact information, etc. </div>
                        </div> 
                    </div>
                </div>
                <div class="eight wide column">
                    <div class="ui fluid card">
                        <div class="content">
                            <img class="ui tiny image left floated" src="../../img/policy.png"> 
                            <div class="header"> Policy & Operations </div>
                            <div class="meta"> Hours, access privileges, borrowing, space reservations, other policies. </div>
                        </div> 
                    </div>
                </div>

                <div class="eight wide column">
                    <form class="ui form">
                        <div class="field">
                            <label>
                                Question Topic
                            </label>
                            <input type="text" name="topic" placeholder="Add topic here." height="200">
                        </div>
                        <div class="grouped fields">
                            <label for="referral">Referral?</label>
                            <div class="field">
                                <div class="ui radio checkbox">
                                    <input type="radio" name="referral" tabindex="0" class="hidden">
                                    <label>Yes</label>
                                </div>
                            </div>
                            <div class="field">
                                <div class="ui radio checkbox">
                                    <input type="radio" name="referral" tabindex="0" class="hidden">
                                    <label>No</label>
                                </div>
                            </div>
                        </div>
                        <div class="field">
                            <label>
                                Department / Unit
                            </label>
                            <div class="ui selection dropdown">
                                <input type="hidden" name="department">
                                <i class="dropdown icon"></i>
                                <div class="default text">
                                    Choose your department
                                </div>
                                <div class="menu">
                                    <div class="item" data-value="none">N/A</div>
                                    <div class="item" data-value="linguistics">Linguistics</div>
                                    <div class="item" data-value="cs">Computer Science</div>
                                    <div class="item" data-value="commstudies">Communications</div>
                                    <div class="item" data-value="arts">Fine Arts</div>
                                </div>
                            </div>
                        </div>
                        <div class="field">
                            <label>Course / Section</label>
                            <input type="text" name="course" placeholder="CRS###/SEC###">
                        </div>
                    </form>
                </div>
            </div>
             <div class="ui equal width aligned grid">
                <div class="eight wide column">
                    <div class="ui equal width aligned grid">
                        <div class="four wide column">
                            <div class="ui inverted segment">
                                <div class="ui tiny inverted statistics">
                                    <div class="statistic">
                                        <div class="value">
                                            0
                                        </div>
                                        <div class="label">
                                            People
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="four wide column">
                            <div class="ui inverted segment">
                                <div class="ui tiny inverted statistics">
                                    <div class="statistic">
                                        <div class="value">
                                            0
                                        </div>
                                        <div class="label">
                                            Minutes
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="ui form">
                          <div class="inline fields">
                            <label>How did you help the patron?</label>
                            <div class="field">
                              <div class="ui radio checkbox">
                                <input type="radio" name="frequency" checked="checked">
                                <label>In-Person</label>
                            </div>
                        </div>
                        <div class="field">
                          <div class="ui radio checkbox">
                            <input type="radio" name="frequency">
                            <label>E-mail</label>
                        </div>
                    </div>
                    <div class="field">
                      <div class="ui radio checkbox">
                        <input type="radio" name="frequency">
                        <label>Telephone</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="eight wide column">
         <form class="ui form">
            <div class="grouped fields">
                <label for="status" style = "font-size: 30px">Patron Status</label>
                <div class="field">
                    <div class="ui radio checkbox">
                        <input type="radio" name="status" tabindex="0" checked="" class="hidden">
                        <label>Unknown</label>
                    </div>
                </div>
                <div class="field">
                    <div class="ui radio checkbox">
                        <input type="radio" name="status" tabindex="0" class="hidden">
                        <label>UCLA undergrad</label>
                    </div>
                </div>
                <div class="field">
                    <div class="ui radio checkbox">
                        <input type="radio" name="status" tabindex="0" class="hidden">
                        <label>UCLA graduate student</label>
                    </div>
                </div>
                <div class="field">
                    <div class="ui radio checkbox">
                        <input type="radio" name="status" tabindex="0" class="hidden">
                        <label>UCLA faculty</label>
                    </div>
                </div>
                <div class="field">
                    <div class="ui radio checkbox">
                        <input type="radio" name="status" tabindex="0" class="hidden">
                        <label>UCLA researcher/other</label>
                    </div>
                </div>
                <div class="field">
                    <div class="ui radio checkbox">
                        <input type="radio" name="status" tabindex="0" class="hidden">
                        <label>UCLA alumnus/a</label>
                    </div>
                </div>
                <div class="field">
                    <div class="ui radio checkbox">
                        <input type="radio" name="status" tabindex="0" class="hidden">
                        <label>non-UCLA</label>
                    </div>
                </div>
            </div>
        </form>
    </div>
            


</div>
</div>


<!--<div class="eight wide column">
    <form class="ui form">
        <div class="field">
            <label>
                Question Topic
            </label>
            <input type="text" name="topic" placeholder="Add topic here." height="200">
        </div>
        <div class="grouped fields">
            <label for="referral">Referral?</label>
            <div class="field">
                <div class="ui radio checkbox">
                    <input type="radio" name="referral" tabindex="0" class="hidden">
                    <label>Yes</label>
                </div>
            </div>
            <div class="field">
                <div class="ui radio checkbox">
                    <input type="radio" name="referral" tabindex="0" class="hidden">
                    <label>No</label>
                </div>
            </div>
        </div>
        <div class="field">
            <label>
                Department / Unit
            </label>
            <div class="ui selection dropdown">
                <input type="hidden" name="department">
                <i class="dropdown icon"></i>
                <div class="default text">
                    Choose your department
                </div>
                <div class="menu">
                    <div class="item" data-value="none">N/A</div>
                    <div class="item" data-value="linguistics">Linguistics</div>
                    <div class="item" data-value="cs">Computer Science</div>
                    <div class="item" data-value="commstudies">Communications</div>
                    <div class="item" data-value="arts">Fine Arts</div>
                </div>
            </div>
        </div>
        <div class="field">
            <label>Course / Section</label>
            <input type="text" name="course" placeholder="CRS###/SEC###">
        </div>
    </form>
</div> 
</div>
</div> !-->

<!-- Directions Modal -->
<div class="ui modal" id="directions-modal">
    <div class="content">
        <div class="header">
            <h1>
                Edit content for Directions
            </h1>
            <div class="ui massive form">
                <div class="field">
                    <label>
                        New count:
                    </label>
                    <input placeholder="E.G.: 42" type="number" min="0" inputmode="numberic" pattern="[0-9]*" id="new-directions-count">
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Lookup Modal -->
<div class="ui modal" id="lookup-modal">
    <div class="content">
        <div class="header">
            <h1>
                Edit content for Lookup
            </h1>
            <div class="ui massive form">
                <div class="field">
                    <label>
                        New count:
                    </label>
                    <input placeholder="E.G.: 42" type="number" min="0" inputmode="numberic" pattern="[0-9]*" id="new-lookup-count">
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Policy Modal -->
<div class="ui modal" id="policy-modal">
    <div class="content">
        <div class="header">
            <h1>
                Edit content for Policy
            </h1>
            <div class="ui massive form">
                <div class="field">
                    <label>
                        New count:
                    </label>
                    <input placeholder="E.G.: 42" type="number" min="0" inputmode="numberic" pattern="[0-9]*" id="new-policy-count">
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Research Modal -->
<div class="ui modal" id="research-modal">
    <div class="content">
        <div class="header">Research Assistance
            <h1>
                Edit content for Research Assistance
            </h1>
            <div class="ui massive form">
                <div class="field">
                    <label>
                        New count:
                    </label>
                    <input placeholder="E.G.: 42" type="number" min="0" inputmode="numberic" pattern="[0-9]*" id="new-research-count">
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Technical Modal -->
<div class="ui modal" id="technical-modal">
    <div class="content">
        <div class="header">
            <h1>
                Edit content for Technical Assistance
            </h1>
            <div class="ui massive form">
                <div class="field">
                    <label>
                        New count:
                    </label>
                    <input placeholder="E.G.: 42" type="number" min="0" inputmode="numberic" pattern="[0-9]*" id="new-technical-count">
                </div>
            </div>
        </div>
    </div>
</div>

</div>

</body>
</html>
        
        

        
        ',
    );
  return $form;
}



/**
 * Returns the form for the second page of form_example_tutorial_8().
 *
 * @ingroup form_example
 */
function statsform_form_page_two($form, &$form_state) {
  $form['description'] = array(
    '#type' => 'item',
    '#title' => t('A basic multistep form (page 2)'),
  );

  $form['color'] = array(
    '#type' => 'textfield',
    '#title' => t('Favorite color'),
    '#required' => TRUE,
    '#default_value' => !empty($form_state['values']['color']) ? $form_state['values']['color'] : '',
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
    '#submit' => array('statsform_form_page_two_submit'),
  );
  $form['back'] = array(
    '#type' => 'submit',
    '#value' => t('<< Back'),
    '#submit' => array('statsform_form_page_two_back'),
    // We won't bother validating the required 'color' field, since they
    // have to come back to this page to submit anyway.
    '#limit_validation_errors' => array(),
  );
  return $form;
}


/**
 * Validate handler for the next button on first page.
 *
 * @ingroup form_example
 */
function statsform_form_next_validate($form, &$form_state) {
  $year_of_birth = $form_state['values']['year_of_birth'];
  if ($year_of_birth && ($year_of_birth < 1900 || $year_of_birth > 2000)) {
    form_set_error('year_of_birth', t('Enter a year between 1900 and 2000.'));
  }
}

/**
 * Submit handler for form_example_tutorial_8() next button.
 *
 * Capture the values from page one and store them away so they can be used
 * at final submit time.
 *
 * @ingroup form_example
 */
function statsform_form_next_submit($form, &$form_state) {

  // Values are saved for each page.
  // to carry forward to subsequent pages in the form.
  // and we tell FAPI to rebuild the form.
  $form_state['page_values'][1] = $form_state['values'];

  if (!empty($form_state['page_values'][2])) {
    $form_state['values'] = $form_state['page_values'][2];
  }

  // When form rebuilds, it will look at this to figure which page to build.
  $form_state['page_num'] = 2;
  $form_state['rebuild'] = TRUE;
}

/**
 * Back button handler submit handler.
 *
 * Since #limit_validation_errors = array() is set, values from page 2
 * will be discarded. We load the page 1 values instead.
 *
 * @ingroup form_example
 */
function statsform_form_page_two_back($form, &$form_state) {
  $form_state['values'] = $form_state['page_values'][1];
  $form_state['page_num'] = 1;
  $form_state['rebuild'] = TRUE;
}

/**
 * The page 2 submit handler.
 *
 * This is the final submit handler. Gather all the data together and output
 * it in a drupal_set_message().
 *
 * @ingroup form_example
 */
function statsform_form_page_two_submit($form, &$form_state) {
  // Normally, some code would go here to alter the database with the data
  // collected from the form. Instead sets a message with drupal_set_message()
  // to validate that the code worked.
  $page_one_values = $form_state['page_values'][1];
  drupal_set_message(t('The form has been submitted. name="@first @last", year of birth=@year_of_birth',
    array(
      '@first' => $page_one_values['first'],
      '@last' => $page_one_values['last'],
      '@year_of_birth' => $page_one_values['year_of_birth'],
    )
  ));

  if (!empty($page_one_values['first2'])) {
    drupal_set_message(t('Second name: name="@first @last", year of birth=@year_of_birth',
      array(
        '@first' => $page_one_values['first2'],
        '@last' => $page_one_values['last2'],
        '@year_of_birth' => $page_one_values['year_of_birth2'],
      )
    ));
  }
  drupal_set_message(t('And the favorite color is @color', array('@color' => $form_state['values']['color'])));

  // If we wanted to redirect on submission, set $form_state['redirect']. For
  // simple redirects, the value can be a string of the path to redirect to. For
  // example, to redirect to /node, one would specify the following:
  //
  // $form_state['redirect'] = 'node';
  //
  // For more complex redirects, this value can be set to an array of options to
  // pass to drupal_goto(). For example, to redirect to /foo?bar=1#baz, one
  // would specify the following:
  //
  // @code
  // $form_state['redirect'] = array(
  //   'foo',
  //   array(
  //     'query' => array('bar' => 1),
  //     'fragment' => 'baz',
  //   ),
  // );
  // @endcode
  //
  // The first element in the array is the path to redirect to, and the second
  // element in the array is the array of options. For more information on the
  // available options, see http://api.drupal.org/url.
}